### PR TITLE
Favour indexer over `getByName`

### PR DESCRIPTION
**Pull request by bamboo**

### CODE REVIEW

**Comment by bmuschko** [comment]
@bamboo Thanks for the PR. Can you elaborate why this is the better choice?

**Comment by bamboo** [comment]
The indexer form is both shorter and [more idiomatic Kotlin](https://kotlinlang.org/docs/reference/idioms.html#accessing-a-map) with equivalent behaviour.

See also: [indexed property access](https://kotlinlang.org/docs/reference/operator-overloading.html#indexed).

**Comment by bmuschko** [comment]
> The indexer form is both shorter and more idiomatic Kotlin with equivalent behaviour.

Cool, what's the behavior if the task with that name cannot be found? Is the value `null` or does the Kotlin DSL throw an exception according to `getByName `?

**Comment by bamboo** [comment]
The indexer is just sugar around `getByName`. The trick to get the docs or to go to the implementation of the indexer is to position the cursor at the first column after the left square bracket:

screen shot 2018-04-16 at 08 25 11

**Comment by bmuschko** [comment]
@bamboo Thanks for clarifying. For some reason I don't get the context information you show in your last comment.

I am going to make this change manually as I already moved the code to `buildSrc`.

**Pull request closed without merging**
